### ISSUE TITLE
[1.12.2] Enderstorage config resets itself when you change "personalItem"

### ISSUE THREAD

**Issue by jawsawn** [TheCBProject/EnderStorage#73] opened 2018-02-18 15:14 UTC
I've been trying to set 
personalItem=minecraft:diamond|0 
as 
personalItem=thermalfoundation:material|6
(diamond nugget from TE)

but everytime I do that and load my client, the config file gets overwritten. 
Using the latest version from curseforge.

**Comment by covers1624** [comment] 2018-05-26 22:33
Duplicate of #68

**Closed as completed by covers1624** 2018-05-26 22:33 UTC
