### ISSUE TITLE
[BUG/1.16.5] Seems like TinkersContruct latest update conflicting with EnderStorage.

### ISSUE THREAD

**Issue by KKotik** [TheCBProject/EnderStorage#176] opened 2021-12-07 08:35 UTC
Recently got the crash with both installed
[crash-2021-12-07_11.28.13-client.txt](https://github.com/TheCBProject/EnderStorage/files/7666805/crash-2021-12-07_11.28.13-client.txt)
On the TiC's bug tracker they staing that this bug from ES side. See more details here:
https://github.com/SlimeKnights/TinkersConstruct/issues/4667

**Comment by covers1624** [comment] 2021-12-07 09:01
Please do not open duplicate issues.

Duplicate of: https://github.com/TheCBProject/CodeChickenLib/issues/384

**Closed as completed by covers1624** 2021-12-07 09:01 UTC

**Comment by KKotik** [comment] 2021-12-07 14:33
Sorry I didn't noticed another one. The title was not informational enoughth.
