### ISSUE TITLE
[1.10.2] Render crash with EnderStorage 84-91

### ISSUE THREAD

**Issue by humroben** [TheCBProject/EnderStorage#25] opened 2016-12-13 02:30 UTC
I've uploaded the full crash report of the error I've been getting with my client when connected to a server with the same mods installed.

http://wiki.citypaine.com/Enderstorage-Error.txt

The server has been tested with and without sponge to test whether or not the rendering error was a product of the server side rendering presented to the client, or client-side rendering. The results were the same. I was initially using the recommended version #84, and then tried with #91. In both cases, the error was the same.

For the time being, I've had to disable this mod on my server, but I would really love to be able to continue using it if at all possible, as it is a very useful mod to have for utilitarian reasons.

_Note: The crash report does mention issues with EnderIO, but the stacktrace shows no evidence that this would be the cause, Since AE2 is not active on the server, due to issues with sponge integration._

**Comment by covers1624** [comment] 2016-12-13 02:33
This is not an issue with EnderStorage, This is some weird vanilla issue rendering a tinkers hammer, It may have something to do with CCL but ill investigate.

**Comment by ktole1999** [comment] 2016-12-13 02:43
you might try turning off the render setting in tinkers construct. there is a setting to render on top of craft tables.

**Comment by covers1624** [comment] 2016-12-13 02:44
You can try but it wont make any difference, This is rendering it in a gui.

**Comment by humroben** [comment] 2016-12-13 03:07
I'll at least try disabling the tinkers rendering, just to see if this has any affect on this. I'll report my findings shortly.

**Comment by humroben** [comment] 2016-12-13 03:13
Okay, so disabling tinker's render setting has made it possible for me to play without issue so far. I've made sure to move around the affected area, and even leave and re-enter the chunk containing the ender chest.

This does confirm that this is in fact due to the rendering between the two mods. Since I'm not a minecraft mod developer, I will not try to speculate what might be causing this, but at least this is known.

Thank you for the suggestion. If an update is released to try and combat this, let me know, and I'll test against my server. Would be nice to contribute with bug testing, I've done my fair share with C++ programming.

**Comment by covers1624** [comment] 2016-12-13 05:19
It has 100% nothing to do with ES, it has to be some weird interaction between CCL and TC. ill poke boni and see what he says.

**Comment by covers1624** [comment] 2017-01-08 18:07
This should be fixed now days. Please verify the issue is fixed with the latest versions of all mods from CB's site.

**Comment by covers1624** [comment] 2017-01-23 07:52
Closed due to no response, assuming fixed.

**Closed as completed by covers1624** 2017-01-23 07:52 UTC
