### ISSUE TITLE
Computercraft turtle resets chest to white/white/white

### ISSUE THREAD

**Issue by ghost** [TheCBProject/EnderStorage#76] opened 2018-03-10 17:54 UTC
Having just Computercraft and EnderStorage loaded (or those and any other mods), when a turtle breaks any color coded chest, it resets the chest to white/white/white.  The config is set to false to reset personal chests.

The config is defaulted on everything.

**Comment by BartAlcorn** [comment] 2018-03-17 12:28
Confirmed that anarchyMode=false in config, but turtles breaking EnderChests reverts them to white/white/white.

**Comment by SquidDev** [comment] 2018-04-12 09:00
Rather late to the party (sorry), but worth noting that this is caused by #70.

It may be worth using [CC:Tweaked](https://minecraft.curseforge.com/projects/cc-tweaked) until that issue is resolved, as that calls the older method, avoiding the problem.

**Comment by covers1624** [comment] 2018-04-12 09:02
Ahh i see, was wondering if it was related, getting back in to the swing of things next week, hopefully some updates to fix this. For now, ill leave this open as a duplicate.

**Comment by covers1624** [comment] 2018-05-26 22:50
Duplicate of #70 and is now marked as fixed in dev. Closing this.

**Closed as completed by covers1624** 2018-05-26 22:50 UTC
Labels: duplicate, bug
