### ISSUE TITLE
when i break the ender storage chest the game and world hard crashes  

### ISSUE THREAD

**Issue by AEther000** [TheCBProject/EnderStorage#201] opened 2022-09-01 20:13 UTC
this is the crash log:

[crash-2022-09-01_22.07.45-client.txt](https://github.com/TheCBProject/EnderStorage/files/9473071/crash-2022-09-01_22.07.45-client.txt)

**Comment by Valtek3724** [comment] 2022-09-02 07:35
same here. 

first crash - i broke a CC turtle with an Ender Chest in its inventory and the game crashed.

second crash - same thing as the first time.

third crash - i broke a vanilla chest with an Ender Chest in its inventory.

fourth crash - after re-installing the ender storage mod, i noticed my old ender chest still in my base.  i broke it with a pickaxe 
                      and crashed again.

i can only assume that the ender chest doesn't like being a floating item on the ground in the world.

my personal fix for now is this:  since my world wouldnt load back up, i had to delete the ender storage mod and then log back into my world, which worked perfectly.  Then i could log back out and redownload the ender storage mod and install it.  i lost a few ender chests in my world, but the point is i saved my world lol. :)

i hope this information helps.

EDIT:  Sorry, i forgot to say that this version is the 1.19.2 mod.

**Comment by covers1624** [comment] 2022-09-02 07:43
Duplicate of https://github.com/TheCBProject/EnderStorage/issues/200

Please see already closed issues before creating a new one.

**Closed as completed by covers1624** 2022-09-02 07:43 UTC
