### ISSUE TITLE
Game crash with JEI

### ISSUE THREAD

**Issue by Visci0** [TheCBProject/EnderStorage#206] opened 2022-12-28 02:23 UTC
Game crashes when pressing U on an ender chest (item), was playing on a friends world and it crashed me but not him (1.18.2 btw)

**Comment by Thollp** [comment] 2023-01-17 17:02
Simple solution: Just don't (accidentally) click U

BTW I want devs to fix this so it can support Recipe book mods (like JEI and REI) and create that I played with because I also get issue like you from create which I explained on #208

**Comment by covers1624** [comment] 2023-01-18 02:58
Closing in favor of #208

**Closed as not planned by covers1624** 2023-01-18 02:58 UTC

**Comment by Thollp** [comment] 2023-01-19 14:58
> Closing in favor of #208

@Visci0
Hi, so technically you need to provide steps to reproduce the bugs/crashes. And also provides crash report
