### ISSUE TITLE
Issue with Refined Storage

### ISSUE THREAD

**Issue by Beckfast1994** [TheCBProject/EnderStorage#152] opened 2021-02-03 20:22 UTC
Hi, I'm super new to this, so hopefully I'm doing this right.

I was playing with the Enigmatica 6 modpack and I wanted to use an Ender Chest as external storage with my Refined Storage system. However whenever I connect an Ender Chest to the External Storage module I can no longer remove items in my Crafting Grid which is really strange. So basically, it prevents me from taking items out of the storage. I'm not sure if I should also be reporting this to Refined Storage and/or Enigmatica...

It works fine with the Ender Tank though and I was able to use an Ender Chest with an importer so I'm really not sure what's going on. Seems strange to me and thought maybe it was an incompatibility issue.

**Comment by covers1624** [comment] 2021-02-03 21:39
EnderStorage is just a regular inventory, I recommend posting an issue with Refined Storage and linking it here.

**Comment by Darkere** [comment] 2021-02-04 07:59
The issue is on RS's side and has been known for a while.. 

I do have to wonder why you are calling a blockupdate every second tho.

**Comment by covers1624** [comment] 2021-08-20 09:11
Calling block update every second has been resolved in dev for 1.17

**Closed as completed by covers1624** 2021-08-20 09:11 UTC
