### ISSUE TITLE
Private Enderchests can be stolen from

### ISSUE THREAD

**Issue by Jamdog** [TheCBProject/EnderStorage#85] opened 2018-06-04 01:59 UTC
I believed that part of the whole point of a Private Enderchest should be that only the person who 'owns' it can open it, or remove items from it?

In fact, it seems that anyone is able to open it, and take stuff from it, even when they are not the owner.  This means that either they aren't working correctly, or the word 'Private' is misleading.

Also, a private enderchest will drop items into a hopper placed below it.

I think it would make far more sense, in terms of servers, if private enderchests were actually private, so that only the owner can open them.  If this is done, then they should also not feed into hoppers placed below them, for security reasons.  Maybe to allow people to use them with hoppers, make a 'Private Enderhopper' for use with Private enderchests, which only works if the owner name matches, but can then feed into vanilla hoppers (or hopper ducts).

If they were never meant to be private, then maybe rename them 'Personal Enderchests'...?

**Comment by covers1624** [comment] 2018-06-04 02:02
Yes, that is the intended behaviour, they are Personal not Private, the chest is in your own frequency space and only you can move it to your frequency space. Where are you getting Private from, ES doesn't have anything ingame that says Private..

**Comment by Ecu** [comment] 2018-06-04 04:38
I'll give my input, @Jamdog ...  No.

Vanilla Ender Chests are already only privately accessible.  Adding private hoppers to the mod is outside the scope of what the mod is intended to offer.  Additionally, even if such a feature was added...it would only serve to delay people from stealing until the items got into your machines.  Do you expect every mod to add privacy features?  I'd wouldn't think so.

There are some server securing mods that exist by logging who placed a block and then only allowing said owner to access it.  I would recommend using something like this instead for server security.  If Ender Storage isn't playing nice with such a logging mod, then I think that might be a worth area to look into.  However, Ender Storage "should" be treated as a normal inventory by other systems and as such "should" work with said systems.  If not, please report it.

My two cents... @covers1624 do what you want with them.  ^-^

**Comment by covers1624** [comment] 2018-06-04 04:43
I agree, Iv'e been thinking the past few hours about a private hopper, it wouldn't really fit. I'm going to close this, Glad the miss communication between the server and you were resolved, and thanks for the suggestion. I may use it for some other projects.

**Closed as completed by covers1624** 2018-06-04 04:43 UTC
